<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-06T12:09:09 IST" name="Suite" finished-at="2023-11-06T12:12:09 IST" duration-ms="180034">
    <groups>
    </groups>
    <test started-at="2023-11-06T12:09:09 IST" name="LATAM_Tester" finished-at="2023-11-06T12:12:09 IST" duration-ms="180034">
      <class name="packtflow3.TestCase3">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:packtflow3.TestCase3@e15b7e8]" started-at="2023-11-06T12:09:09 IST" name="beforeClass" finished-at="2023-11-06T12:09:10 IST" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:packtflow3.TestCase3@e15b7e8]" started-at="2023-11-06T12:09:10 IST" name="beforeTest" finished-at="2023-11-06T12:09:16 IST" duration-ms="6744" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="TestCase001()[pri:0, instance:packtflow3.TestCase3@e15b7e8]" started-at="2023-11-06T12:09:16 IST" name="TestCase001" finished-at="2023-11-06T12:12:08 IST" duration-ms="171669" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Page title does not match the expected title. expected [Preface | Machine Learning Engineering with Python] but found [Preface | Machine Learning Engineering with Python - Second Edition]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Page title does not match the expected title. expected [Preface | Machine Learning Engineering with Python] but found [Preface | Machine Learning Engineering with Python - Second Edition]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at packtflow3.TestCase3.TestCase001(TestCase3.java:356)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase001 -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:packtflow3.TestCase3@e15b7e8]" started-at="2023-11-06T12:12:08 IST" name="afterTest" finished-at="2023-11-06T12:12:09 IST" duration-ms="939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:packtflow3.TestCase3@e15b7e8]" started-at="2023-11-06T12:12:09 IST" name="afterClass" finished-at="2023-11-06T12:12:09 IST" duration-ms="306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- packtflow3.TestCase3 -->
    </test> <!-- LATAM_Tester -->
  </suite> <!-- Suite -->
</testng-results>
